### ISSUE TITLE
"The post was not saved to the repository"

### ISSUE THREAD

**Issue by RoneoOrg** [pyrmont/pondent#18]
Hi there,

I tested Pondent and got the following error at the top of the page while hiting the "Post" button:

```
Save Failed

The post was not saved to the repository. The server returned the following response:

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"
}
```

I double checked the settings. Here they are:

```
Settings
Owner: RoneoOrg
Repo: hugo-theme-hexandcube
Branch: master

Posts
Directory: content/posts/
Commit: Pondent edit

Uploads
Directory: static/
URL: /
Commit: Pondent upload

GitHub
User: RoneoOrg
Token: ghp_z[...]
```

The corresponding repo: https://github.com/RoneoOrg/hugo-theme-hexandcube

Any hint?

**Comment by pyrmont** [comment]
Are you using the personal access token because the 'Authorise with GitHub' button didn't work? I've recently changed something on the backend and while I thought that was working, I just tested it again and it redirects me to a page saying 'Authorising…' that never goes anywhere.

The personal access token should work, too, but perhaps something's changed with how Pondent is supposed to send that and it's causing the error.

**Comment by pyrmont** [comment]
The 'Authorise with GitHub' button was indeed broken. A mistake on my part as part of the change from using a Heroku dyno as a proxy to using a Cloudflare Worker. It should be working now. Let me know if when you log in that way, you're able to post.

**Comment by RoneoOrg** [comment]
Yes it's working fine now, thanks!

**Comment by pyrmont** [comment]
Thanks for letting me know! I'll also make a note to investigate what's going on with the personal token setting. That should have worked unless GitHub's changed something.
